malvina integration
handleError: anException withResult: aResult

	self announceTestException: anException