tests
testError

	self error: 'Error!'