tests
testExpectedFailure
	<expectedFailure>
	self error: 'Error!'